name: Deploy to EC2 with SCP and Docker Compose

on:
  push:
    branches: [master] # デプロイをトリガーするブランチを指定

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SCP files to EC2
        run: |
          pwd # 現在のディレクトリを出力
          ls -la # 現在のディレクトリの内容をリストアップ
          scp -o "StrictHostKeyChecking=no" -r /home/runner/work/product-register/product-register ${{ secrets.USER }}@${{ secrets.HOST }}:./myapp

      - name: Deploy with Docker Compose
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USER }}@${{ secrets.HOST }} '
            pwd
            ls -a
            cd ./myapp/product-register
            ls -a
            pwd
            sudo docker-compose down
            sudo docker-compose up -d --build
          '
